# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f85f0239e888f264001de7d6846fb65a31d302e79518a796ee48658879af2ea557092690bfe7f321f5520c0ad90eff9d8d8bbd0990b9b01da40b49f3c1da6bc

test:
  secret_key_base: 86b91f393fbf72f3c1889aad4c49739e9a5056ad2c56392147b53c046a5e886cdc11ad0d046849c502dbd31c34d8995cfa731c96a447b7115890c99379659a43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
